=== nivinskumar/routerservice/src/main/resources/schema/routing.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="workflow">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="constructiontype" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="id" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="description" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element ref="milestone" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="milestone">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="id" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="description" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element ref="task" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="task">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="id" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="description" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="tasktype" type="tasktype" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="uibean" type="uiBean" minOccurs="0" maxOccurs="1" />
				<xs:element name="endpoint" type="endPoint" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="successorid" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="predecessorid" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="sla-exec" type="xs:string" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="sla-metrics" type="xs:string"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="sla-pickup-min" type="xs:string"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="phase-id" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="queue-id" type="xs:string" minOccurs="1"
					maxOccurs="1" />

				<xs:element ref="subtask" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="subtask">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="id" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="description" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="subtasktype" type="tasktype" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="uibean" type="uiBean" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="endpoint" type="endPoint" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="successorid" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="predecessorid" type="xs:string"
					minOccurs="1" maxOccurs="1" />
				<xs:element name="sla-exec" type="xs:string" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="sla-metrics" type="xs:string"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="sla-pickup-min" type="xs:string"
					minOccurs="0" maxOccurs="1" />
				<xs:element name="phase-id" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="queue-id" type="xs:string" minOccurs="1"
					maxOccurs="1" />
				<xs:element name="concurrent" type="xs:boolean"
					minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="tasktype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="HUMAN" />
			<xs:enumeration value="SYSTEM" />
			<xs:enumeration value="EVENT" />
			<xs:enumeration value="EMAIL" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="uiBean">
		<xs:restriction base="xs:string">
			<xs:enumeration value="com.immco.survey.SurveyUI" />
			<xs:enumeration value="com.immco.survey.EstimatePopup" />
			<xs:enumeration value="com.immco.survey.WalkoutUI" />
			<xs:enumeration value="com.immco.survey.RoiUI" />
		</xs:restriction>
	</xs:simpleType>
	
		<xs:simpleType name="endPoint">
		<xs:restriction base="xs:string">
			<xs:enumeration value="/surveyComplete" />
			<xs:enumeration value="/estimateComplete" />
			<xs:enumeration value="/estimateSupApprove" />
			<xs:enumeration value="/walkoutComplete" />
			<xs:enumeration value="/designComplete" />
			<xs:enumeration value="/permitComplete" />
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== nivinskumar/routerservice/src/main/resources/schema/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="routing.xsd">
	<constructiontype>SMB COAX</constructiontype>
	<name>SMB_COAX_WF_1</name>
	<id>SMB_COAX_WF_1</id>
	<description>Workflow for SMB Coax</description>
	<milestone>
		<name>M1</name>
		<id>M1</id>
		<description>MILESTONE-1</description>
		<task>
			<name>SURVEY</name>
			<id>S-1</id>
			<description>DO SURVEY</description>
			<tasktype>HUMAN</tasktype>
			<uibean>com.immco.survey.SurveyUI</uibean>
			<endpoint>/surveyComplete</endpoint>
			<successorid></successorid>
			<predecessorid></predecessorid>
			<sla-exec>10</sla-exec>
			<sla-metrics>0</sla-metrics>
			<sla-pickup-min></sla-pickup-min>
			<phase-id>SERVICEABILITY</phase-id>
			<queue-id>SURVEY</queue-id>
			<subtask>
				<name>ESTIMATE</name>
				<id>S-1-E-1</id>
				<description>DO ESTIMATE</description>
				<subtasktype>HUMAN</subtasktype>
				<uibean>com.immco.survey.EstimatePopup</uibean>
				<endpoint>/estimateComplete</endpoint>
				<successorid>S-1-E-2</successorid>
				<predecessorid></predecessorid>
				<sla-exec></sla-exec>
				<sla-metrics></sla-metrics>
				<sla-pickup-min></sla-pickup-min>
				<phase-id>SERVICEABILITY</phase-id>
				<queue-id>SURVEY</queue-id>
				<concurrent>false</concurrent>
			</subtask>
			<subtask>
				<name>ESTIMATE-SUP-APPROVE</name>
				<id>S-1-E-2</id>
				<description>APPROVE ESTIMATE BY SUPERVISOR</description>
				<subtasktype>HUMAN</subtasktype>
				<endpoint>/estimateSupApprove</endpoint>
				<successorid></successorid>
				<predecessorid>S-1-E-1</predecessorid>
				<sla-exec></sla-exec>
				<sla-metrics></sla-metrics>
				<sla-pickup-min></sla-pickup-min>
				<phase-id>SERVICEABILITY</phase-id>
				<queue-id>SURVEY</queue-id>
				<concurrent>false</concurrent>
			</subtask>
		</task>
	</milestone>

	<milestone>
		<name>M2</name>
		<id>M2</id>
		<description>MILESTONE-2</description>
		<task>
			<name>WALKOUT</name>
			<id>W-1</id>
			<description>DO WALKOUT</description>
			<tasktype>HUMAN</tasktype>
			<uibean>com.immco.survey.WalkoutUI</uibean>
			<endpoint>/walkoutComplete</endpoint>
			<successorid></successorid>
			<predecessorid></predecessorid>
			<sla-exec>35</sla-exec>
			<sla-metrics>0</sla-metrics>
			<sla-pickup-min></sla-pickup-min>
			<phase-id>SERVICEABILITY</phase-id>
			<queue-id>WALKOUT</queue-id>
			<subtask>
				<name>ESTIMATE</name>
				<id>W-1-E-1</id>
				<description>DO ESTIMATE REVISION</description>
				<subtasktype>HUMAN</subtasktype>
				<uibean>com.immco.survey.EstimatePopup</uibean>
				<endpoint>/estimateComplete</endpoint>
				<successorid></successorid>
				<predecessorid></predecessorid>
				<sla-exec></sla-exec>
				<sla-metrics></sla-metrics>
				<sla-pickup-min></sla-pickup-min>
				<phase-id>SERVICEABILITY</phase-id>
				<queue-id>WALKOUT</queue-id>
				<concurrent>false</concurrent>
			</subtask>
		</task>
	</milestone>
</workflow>
